# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.build_dir = "."
    docker.build_args = ["--build-arg", "SCRIPT_SOURCE=vagrantize-docker.sh"]
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
    docker.create_args = ["--cgroupns=host"]
    docker.cmd = ["/usr/sbin/init"]
  end


end
